language: java

services:
  - docker

before_install:
  - echo -e "docker stuff"
  - docker ps -a
  # - export DOCKER_HOST=`docker run --network host eclipse/che-ip`
  - echo $DOCKER_HOST
  - sudo ip link add dummy1 type dummy
  - sudo ip link set dev dummy1 up
  - ip link show type dummy

  - sudo ip addr add 169.254.1.1/32 dev dummy0
  - sudo ip link set dev dummy1 up
  - ip addr show dev dummy1

  - cat /etc/hosts
  - sudo echo "169.254.1.1 host.docker.internal" >> /etc/hosts
  - cat /etc/hosts


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/